import React from 'react';
import {
  IconAnchor,
  IconArrowLeft,
  IconArrowRight,
  IconBarrierBlock,
  IconBellFilled,
  IconChartInfographic,
  IconChevronDown,
  IconChevronLeft,
  IconChevronsLeft,
  IconChevronsRight,
  IconChevronUp,
  IconCircleChevronRight,
  IconDatabase,
  IconDatabaseCog,
  IconDatabasePlus,
  IconDatabaseSearch,
  IconDatabaseShare,
  IconDiamondsFilled,
  IconDownload,
  IconExternalLink,
  IconHome,
  IconInfoCircleFilled,
  IconLayoutSidebarLeftCollapse,
  IconLayoutSidebarLeftExpand,
  IconLink,
  IconListSearch,
  IconMenu,
  IconReport,
  IconReportSearch,
  IconSearch,
  IconSquareRoundedArrowRight,
  IconSquareRoundedChevronLeftFilled,
  IconUserCog,
  IconX,
  TablerIconsProps,
} from '@tabler/icons-react';

export const Icons: {
  [key: string]: (props: TablerIconsProps) => React.ReactElement;
} = {
  back: IconArrowLeft,
  logo: IconAnchor,
  dataset: IconDatabase,
  datasetSettings: IconDatabaseCog,
  addDataset: IconDatabasePlus,
  userSettings: IconUserCog,
  arrowRight: IconArrowRight,
  up: IconChevronUp,
  down: IconChevronDown,
  right: IconCircleChevronRight,
  left: IconChevronLeft,
  doubleLeft: IconChevronsLeft,
  doubleRight: IconChevronsRight,
  leftFilled: IconSquareRoundedChevronLeftFilled,
  search: IconSearch,
  notification: IconBellFilled,
  department: IconListSearch,
  scheme: IconReportSearch,
  cardLink: IconSquareRoundedArrowRight,
  info: IconInfoCircleFilled,

  construction: IconBarrierBlock,
  link: IconLink,
  collapse: IconLayoutSidebarLeftCollapse,
  expand: IconLayoutSidebarLeftExpand,
  home: IconHome,
  overview: IconReport,
  explorer: IconChartInfographic,
  databaseShare: IconDatabaseShare,
  databaseSearch: IconDatabaseSearch,
  download: IconDownload,
  diamond: IconDiamondsFilled,
  externalLink: IconExternalLink,
  menu: IconMenu,
  cross: IconX,
};

export default Icons;
